### ISSUE TITLE
docs: line mode 'pet-id' 쿼리 파라미터 설명 추가

### ISSUE THREAD

**Issue by csct3434** [devxb/gitanimals-render#31]
<img width="794" alt="image" src="https://github.com/devxb/gitanimals/assets/107951175/08817660-b372-4501-be91-7fe7be958bda">

---

안녕하세요, 서비스 잘 이용하고 있습니다 ㅎㅎ
line mode의 pet-id가 쿼리 파라미터임을 따로 명시하거나 코드 예시에 포함되어 있으면 좋을거 같아요!

**Comment by devxb** [comment]
[005e10e](https://github.com/devxb/gitanimals/commit/005e10ed0c134833138e01af169e1a1b7383546d)

의견감사합니다 :)
수정해서 반영했습니다
